#!/usr/bin/env python3
"""
contradiction_detector.py — Detect contradictory or conflicting conclusions
within the same or across related themes using semantic opposition and
claim-level analysis.

Usage
-----
    python contradiction_detector.py
        [--papers search_results.csv]
        [--consensus consensus_themes.csv]
"""

from __future__ import annotations

import argparse
import logging
import re
from collections import Counter, defaultdict
from datetime import datetime
from itertools import combinations
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("contradiction_detector")

OPPOSITE_PAIRS = [
    ("increase", "decrease"),
    ("positive", "negative"),
    ("beneficial", "harmful"),
    ("improve", "worsen"),
    ("support", "oppose"),
    ("effective", "ineffective"),
    ("significant", "insignificant"),
    ("enhance", "reduce"),
    ("facilitate", "hinder"),
    ("promote", "suppress"),
    ("strengthen", "weaken"),
    ("accelerate", "slow"),
    ("success", "failure"),
    ("advantage", "disadvantage"),
    ("enable", "prevent"),
]


def extract_claims(text: str) -> List[str]:
    """Extract candidate claim sentences from abstract."""
    if not text or str(text).lower() in ("nan", "none", ""):
        return []
    text = str(text)
    # Split into sentences
    sentences = re.split(r"[.!?]\s+", text)
    claims = []
    for s in sentences:
        s = s.strip()
        if len(s) < 20:
            continue
        # Look for claim-like patterns
        if re.search(r"\b(found|show|suggest|indicate|demonstrate|reveal|confirm|imply|result|conclude|observe|report|identify|establish|determine)\b", s, re.IGNORECASE):
            claims.append(s[:200])
    return claims[:5]


def find_semantic_opposites(
    df: pd.DataFrame,
    model: SentenceTransformer,
    threshold: float = 0.75,
) -> List[Dict]:
    """Find pairs of abstracts with high semantic similarity but opposite
    directional claims."""
    texts = (df["title"].fillna("") + ". " + df["abstract"].fillna("")).tolist()
    if len(texts) < 2:
        return []

    log.info("Encoding %d texts for contradiction detection...", len(texts))
    embs = model.encode(texts, show_progress_bar=True, batch_size=32)
    sim_matrix = util.cos_sim(embs, embs).numpy()

    contradictions: List[Dict] = []
    for i, j in combinations(range(len(texts)), 2):
        if sim_matrix[i][j] < threshold:
            continue

        # Check for opposite claim structures
        t_i = texts[i].lower()
        t_j = texts[j].lower()
        opposite_found = False
        for a, b in OPPOSITE_PAIRS:
            has_a_i = re.search(rf"\b{a}\b", t_i)
            has_b_j = re.search(rf"\b{b}\b", t_j)
            has_b_i = re.search(rf"\b{b}\b", t_i)
            has_a_j = re.search(rf"\b{a}\b", t_j)
            if (has_a_i and has_b_j) or (has_b_i and has_a_j):
                opposite_found = True
                break

        if opposite_found:
            contradictions.append({
                "paper_a_doi": str(df.iloc[i].get("doi", "")),
                "paper_a_title": str(df.iloc[i].get("title", ""))[:120],
                "paper_b_doi": str(df.iloc[j].get("doi", "")),
                "paper_b_title": str(df.iloc[j].get("title", ""))[:120],
                "similarity": round(float(sim_matrix[i][j]), 3),
                "theme_a": str(df.iloc[i].get("consensus_theme", "")),
                "theme_b": str(df.iloc[j].get("consensus_theme", "")),
            })

    contradictions.sort(key=lambda x: x["similarity"], reverse=True)
    return contradictions


def rank_confidence(contradiction: Dict) -> str:
    """Assign confidence label based on similarity."""
    sim = contradiction.get("similarity", 0)
    if sim >= 0.9:
        return "High"
    elif sim >= 0.8:
        return "Medium"
    return "Low"


def _generate_report(contradictions: List[Dict], n_papers: int) -> str:
    lines: List[str] = []
    lines.append("# Contradictory Findings Report")
    lines.append("")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"- **Corpus:** {n_papers} papers")
    lines.append(f"- **Contradictory pairs detected:** {len(contradictions)}")
    lines.append("")

    if not contradictions:
        lines.append("No strong contradictions detected in the current corpus.\n")
        lines.append("This may indicate thematic coherence or limited coverage of opposing viewpoints.")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by contradiction_detector.py*")
        return "\n".join(lines)

    for i, c in enumerate(contradictions, 1):
        conf = rank_confidence(c)
        lines.append(f"### Contradiction {i} (Confidence: {conf})")
        lines.append("")
        lines.append("| | Paper A | Paper B |")
        lines.append("|---|---------|---------|")
        lines.append(f"| **Title** | {c['paper_a_title'][:80]} | {c['paper_b_title'][:80]} |")
        lines.append(f"| **Theme** | {c['theme_a']} | {c['theme_b']} |")
        lines.append(f"| **Similarity** | {c['similarity']} | {c['similarity']} |")
        lines.append("")
        lines.append("**Potential Explanation:**")
        lines.append("Papers share high semantic similarity but use opposing directional language. ")
        lines.append("This may reflect conflicting empirical findings, different contexts, ")
        lines.append("or methodological differences in measurement.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by contradiction_detector.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Detect contradictory findings across papers.")
    parser.add_argument("--papers", type=str, default="search_results.csv")
    parser.add_argument("--consensus", type=str, default="consensus_themes.csv")
    parser.add_argument("--threshold", type=float, default=0.75, help="Similarity threshold")
    args = parser.parse_args()

    papers_path = Path(args.papers)
    if not papers_path.exists():
        log.error("Papers file not found: %s", papers_path)
        return
    df = pd.read_csv(args.papers)
    consensus_path = Path(args.consensus)
    if consensus_path.exists():
        df_c = pd.read_csv(consensus_path)
        merge_cols = [c for c in ["doi", "title"] if c in df_c.columns and c in df.columns]
        if merge_cols:
            df = df.merge(df_c[merge_cols + ["consensus_theme"]], on=merge_cols[0], how="left", suffixes=("", "_consensus"))
            if "consensus_theme" not in df.columns:
                df["consensus_theme"] = df.get("consensus_theme_consensus", "")

    log.info("Loaded %d papers", len(df))
    model = SentenceTransformer("all-MiniLM-L6-v2")
    contradictions = find_semantic_opposites(df, model, threshold=args.threshold)

    out_dir = Path("outputs") / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)

    if contradictions:
        cdf = pd.DataFrame(contradictions)
        cdf["confidence"] = cdf.apply(rank_confidence, axis=1)
        cdf.to_csv(out_dir / "claim_conflicts.csv", index=False)
        log.info("Saved %d -> %s", len(cdf), out_dir / "claim_conflicts.csv")

    report = _generate_report(contradictions, len(df))
    report_path = out_dir / "contradictory_findings.md"
    with open(report_path, "w") as f:
        f.write(report)
    log.info("Saved -> %s", report_path)

    print(f"\n--- Contradiction Detection Complete ---")
    print(f"  Pairs analysed:  {len(list(combinations(range(len(df)), 2)))}")
    print(f"  Contradictions:  {len(contradictions)}")
    print()


if __name__ == "__main__":
    main()
