#!/usr/bin/env python3
"""
evidence_synthesis.py — Compare findings across studies to extract consensus,
identify disagreements, and rank evidence strength per claim.

Outputs
-------
outputs/evidence/evidence_matrix.csv      (extends the existing matrix)
outputs/evidence/evidence_synthesis_report.md
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("evidence_synthesis")

MODEL_NAME = "all-MiniLM-L6-v2"


def load_evidence_matrix(path: str = "outputs/evidence/evidence_matrix.csv") -> pd.DataFrame:
    p = Path(path)
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


def load_knowledge_base(path: str = "knowledge_base.json") -> Dict:
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else {}


def compare_studies(evidence_df: pd.DataFrame, kb: Dict) -> pd.DataFrame:
    """Group papers by theme, compare objectives/methods/results, flag disagreements."""
    rows = []
    theme_papers: Dict[str, List] = defaultdict(list)
    for t in kb.get("themes", []):
        theme_papers[t["theme"]] = t.get("papers", [])

    model = SentenceTransformer(MODEL_NAME, device="cpu")

    for _, row in evidence_df.iterrows():
        title = str(row.get("Title", ""))
        doi = str(row.get("DOI", ""))
        objective = str(row.get("Objective", ""))
        methods = str(row.get("Methods", ""))
        results = str(row.get("Results", ""))
        limitations = str(row.get("Limitations", ""))

        # Find which theme(s) this paper belongs to
        matched_themes = [t for t, papers in theme_papers.items() if any(p in title for p in papers[:3])]

        # Consensus: if multiple papers in same theme report similar results
        consensus = 0.5
        disagreements: List[str] = []

        for theme in matched_themes:
            siblings = [e for e in evidence_df.itertuples()
                        if str(e.Title)[:40] != title[:40]
                        and any(p in str(e.Title) for p in theme_papers.get(theme, [])[:3])]
            for sib in siblings:
                # Compare results via embedding similarity
                r1 = model.encode([results[:200]], show_progress_bar=False)[0]
                r2 = model.encode([str(sib.Results)[:200]], show_progress_bar=False)[0]
                sim = float(np.dot(r1 / np.linalg.norm(r1), r2 / np.linalg.norm(r2)))
                if sim > 0.7:
                    consensus = min(consensus + 0.1, 1.0)
                elif sim < 0.3:
                    disagreements.append(str(sib.Title)[:60])

        rows.append({
            "paper_title": title[:120],
            "doi": doi,
            "themes": "; ".join(matched_themes),
            "objective": objective[:150],
            "methods": methods[:150],
            "results": results[:150],
            "limitations": limitations[:150],
            "consensus_score": round(consensus, 3),
            "disagreements": "; ".join(disagreements[:3]),
            "evidence_rank": "High" if consensus > 0.7 else "Moderate" if consensus > 0.4 else "Low",
        })

    return pd.DataFrame(rows)


def _generate_synthesis_report(df: pd.DataFrame) -> str:
    lines: List[str] = []
    lines.append("# Evidence Synthesis Report\n")
    lines.append(f"- **Studies compared:** {len(df)}")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    lines.append("## Consensus Findings\n")
    high = df[df["evidence_rank"] == "High"]
    for _, row in high.iterrows():
        lines.append(f"- **{row['paper_title']}** (consensus: {row['consensus_score']:.2f})")
        lines.append(f"  - Results: {row['results'][:100]}")

    lines.append("\n## Disagreements\n")
    dis = df[df["disagreements"] != ""]
    for _, row in dis.iterrows():
        lines.append(f"- {row['paper_title']} disagrees with: {row['disagreements']}")

    lines.append("\n## Evidence Ranks\n")
    for rank in ["High", "Moderate", "Low"]:
        c = len(df[df["evidence_rank"] == rank])
        lines.append(f"- **{rank}:** {c} studies")

    lines.append("\n---\n*Generated by evidence_synthesis.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Synthesise evidence across studies.")
    parser.add_argument("--evidence", type=str, default="outputs/evidence/evidence_matrix.csv")
    parser.add_argument("--knowledge-base", type=str, default="knowledge_base.json")
    parser.add_argument("--output-dir", type=str, default="outputs/evidence")
    args = parser.parse_args()

    evidence_df = load_evidence_matrix(args.evidence)
    kb = load_knowledge_base(args.knowledge_base)

    df = compare_studies(evidence_df, kb)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if not df.empty:
        df.to_csv(out_dir / "evidence_matrix.csv", index=False)
        log.info("Saved -> %s", out_dir / "evidence_matrix.csv")

    report = _generate_synthesis_report(df)
    with open(out_dir / "evidence_synthesis_report.md", "w") as f:
        f.write(report)
    log.info("Saved -> %s", out_dir / "evidence_synthesis_report.md")

    print(f"\n--- Evidence Synthesis Complete ---")
    print(f"  Studies compared: {len(df)}")
    print()


if __name__ == "__main__":
    main()
