#!/usr/bin/env python3
"""
grant_proposal_copilot.py — Generate grant proposal components including
specific aims, background, significance, innovation, approach, and
expected outcomes based on research gaps and opportunity rankings.

Outputs
-------
outputs/grants/grant_concept.md
outputs/grants/specific_aims.md
outputs/grants/project_summary.md
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("grant_copilot")


def load_inputs(kb_path: str, gaps_path: str, opportunities_path: str) -> Dict[str, Any]:
    kb = json.load(open(kb_path)) if Path(kb_path).exists() else {}
    gaps_md = Path(gaps_path).read_text() if Path(gaps_path).exists() else ""
    opp = pd.read_csv(opportunities_path) if Path(opportunities_path).exists() else pd.DataFrame()
    return {"kb": kb, "gaps": gaps_md, "opportunities": opp}


def generate_grant_concept(data: Dict[str, Any]) -> str:
    kb = data["kb"]
    gaps = data["gaps"]

    lines: List[str] = []
    lines.append("# Grant Concept\n")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    top_theme = kb.get("themes", [{}])[0].get("theme", "Research Topic")
    lines.append(f"## Title\n")
    lines.append(f"Advancing Understanding of {top_theme}: A Multi-Method Investigation\n")

    lines.append("## Background\n")
    corpus_size = kb.get("corpus_size", 0)
    theme_count = kb.get("theme_count", 0)
    lines.append(f"The literature comprises {corpus_size} papers across {theme_count} thematic clusters. ")
    lines.append(f"The **{top_theme}** theme is the most prominent with {kb.get('themes', [{}])[0].get('paper_count', 0)} papers.\n")

    lines.append("## Rationale\n")
    if gaps:
        lines.append(gaps[:500])
        lines.append("")
    lines.append("This gap underscores the need for targeted empirical investigation.\n")

    lines.append("## Expected Impact\n")
    lines.append("- Advance theoretical understanding of {top_theme}")
    lines.append("- Provide evidence-based recommendations for policy and practice")
    lines.append("- Establish foundation for future longitudinal research\n")

    lines.append("---\n*Generated by grant_proposal_copilot.py*")
    return "\n".join(lines)


def generate_specific_aims(data: Dict[str, Any]) -> str:
    kb = data["kb"]
    opp = data["opportunities"]

    lines: List[str] = []
    lines.append("# Specific Aims\n")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    themes = kb.get("themes", [])
    for i, t in enumerate(themes[:3], 1):
        label = t.get("theme", "")
        lines.append(f"Aim {i}: Characterise the landscape of {label}")
        lines.append(f"  - **Hypothesis:** {label} is associated with key outcomes in this domain")
        lines.append(f"  - **Approach:** Systematic analysis of {t.get('paper_count', 0)} papers using mixed methods")
        lines.append(f"  - **Expected outcome:** Comprehensive understanding of {label}\n")

    if not opp.empty:
        top_opp = opp.head(1)
        lines.append(f"Aim 4: Validate and extend the highest-opportunity theme")
        if "theme" in top_opp.columns:
            lines.append(f"  - **Theme:** {top_opp.iloc[0]['theme']}")
        lines.append(f"  - **Score:** {top_opp.iloc[0].get('opportunity_score', 'N/A')}\n")

    lines.append("---\n*Generated by grant_proposal_copilot.py*")
    return "\n".join(lines)


def generate_project_summary(data: Dict[str, Any]) -> str:
    kb = data["kb"]
    opp = data["opportunities"]

    lines: List[str] = []
    lines.append("# Project Summary\n")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    lines.append("## Significance\n")
    lines.append(f"This project addresses critical gaps in the literature on {kb.get('themes', [{}])[0].get('theme', 'the field')}. ")
    lines.append(f"The corpus of {kb.get('corpus_size', 0)} papers reveals {kb.get('theme_count', 0)} thematic clusters, ")
    lines.append("each representing a distinct avenue for scientific inquiry.\n")

    lines.append("## Innovation\n")
    lines.append("This proposal employs a multi-method consensus approach combining qualitative synthesis, ")
    lines.append("quantitative bibliometric analysis, and computational text mining. ")
    lines.append("The integration of these methods provides a novel triangulation strategy.\n")

    lines.append("## Approach\n")
    lines.append("**Phase 1:** Systematic literature review and evidence extraction")
    lines.append("\n**Phase 2:** Thematic analysis and gap validation")
    lines.append("\n**Phase 3:** Empirical investigation of priority themes")
    lines.append("\n**Phase 4:** Synthesis, recommendations, and dissemination\n")

    if not opp.empty:
        lines.append("## High-Opportunity Areas\n")
        for _, row in opp.head(3).iterrows():
            theme = row.get("theme", "Unknown")
            score = row.get("opportunity_score", "N/A")
            lines.append(f"- {theme} (opportunity score: {score})")

    lines.append("\n## Expected Outcomes\n")
    lines.append("- Peer-reviewed publications in high-impact journals")
    lines.append("- Evidence-based policy recommendations")
    lines.append("- Open-access datasets and analysis code")
    lines.append("- Foundation for future grant applications\n")

    lines.append("---\n*Generated by grant_proposal_copilot.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate grant proposals.")
    parser.add_argument("--knowledge-base", type=str, default="knowledge_base.json")
    parser.add_argument("--gaps", type=str, default="outputs/reports/research_gaps.md")
    parser.add_argument("--opportunities", type=str, default="outputs/reports/research_opportunities.csv")
    parser.add_argument("--output-dir", type=str, default="outputs/grants")
    args = parser.parse_args()

    data = load_inputs(args.knowledge_base, args.gaps, args.opportunities)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sections = {
        "grant_concept": generate_grant_concept(data),
        "specific_aims": generate_specific_aims(data),
        "project_summary": generate_project_summary(data),
    }

    for name, content in sections.items():
        path = out_dir / f"{name}.md"
        with open(path, "w") as f:
            f.write(content)
        log.info("Saved -> %s", path)

    print(f"\n--- Grant Proposal Copilot Complete ---")
    print(f"  Sections: {len(sections)}")
    print()


if __name__ == "__main__":
    main()
