#!/usr/bin/env python3
"""
manuscript_copilot.py — Generate publication-ready manuscript drafts using
evidence matrix, consensus themes, and APA references.

Outputs
-------
outputs/manuscript/introduction.md
outputs/manuscript/literature_review.md
outputs/manuscript/methods_draft.md
outputs/manuscript/discussion_draft.md
outputs/manuscript/references.md
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("manuscript_copilot")


def load_evidence_matrix(path: str = "outputs/evidence/evidence_matrix.csv") -> pd.DataFrame:
    p = Path(path)
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


def load_knowledge_base(path: str = "knowledge_base.json") -> Dict:
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else {}


def load_claim_refs(path: str = "outputs/references/claim_support_references.csv") -> pd.DataFrame:
    p = Path(path)
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


def _inline_cite(row) -> str:
    authors = str(row.get("authors", ""))
    year = row.get("year", "")
    if not authors or authors == "nan":
        if year and year != "nan":
            return f"({int(float(year))})"
        return "(n.d.)"
    parts = re.split(r"[;,]+\s*", authors)
    first = parts[0].strip().split()[-1] if parts else "Author"
    year_str = str(int(float(year))) if year and year != "nan" else "n.d."
    if len(parts) >= 3:
        return f"({first} et al., {year_str})"
    elif len(parts) == 2:
        second = parts[1].strip().split()[-1]
        return f"({first} & {second}, {year_str})"
    else:
        return f"({first}, {year_str})"


def _format_apa(row) -> str:
    authors = str(row.get("authors", ""))
    year = row.get("year", "")
    title = str(row.get("title", "")).strip()
    venue = str(row.get("venue", ""))
    doi = str(row.get("doi", ""))

    if authors and authors != "nan":
        parts = re.split(r"[;,]+\s*", authors)
        formatted = []
        for p in parts:
            tokens = p.strip().split()
            if len(tokens) >= 2:
                last = tokens[-1]
                initials = " ".join(t[0] + "." for t in tokens[:-1])
                formatted.append(f"{last}, {initials}")
            elif tokens:
                formatted.append(tokens[0])
        if len(formatted) == 1:
            author_part = formatted[0]
        elif len(formatted) == 2:
            author_part = f"{formatted[0]} & {formatted[1]}"
        else:
            author_part = ", ".join(formatted[:-1]) + f", & {formatted[-1]}"
    else:
        author_part = "Unknown"

    year_str = str(int(float(year))) if year and year != "nan" and float(year) != 0 else "n.d."
    ref = f"{author_part} ({year_str}). {title}."

    if venue and venue != "nan":
        ref += f" *{venue}*."
    if doi and doi != "nan":
        ref += f" https://doi.org/{doi}"
    return ref


def generate_introduction(kb: Dict, evidence_df: pd.DataFrame, papers_df: pd.DataFrame) -> str:
    lines: List[str] = []
    lines.append("# Introduction\n")
    corpus_size = kb.get("corpus_size", 0)
    theme_count = kb.get("theme_count", 0)
    lines.append(f"The field encompasses {corpus_size} publications spanning {theme_count} thematic clusters. ")
    lines.append(f"This literature review systematically maps the landscape of {kb.get('themes', [{}])[0].get('theme', 'the field')} and related domains.\n")

    lines.append("## Background\n")
    for t in kb.get("themes", [])[:3]:
        label = t.get("theme", "")
        pc = t.get("paper_count", 0)
        conf = t.get("confidence", 0)
        lines.append(f"The **{label}** theme comprises {pc} papers (confidence: {conf:.0%}), representing a substantial body of work on {', '.join(t.get('keywords', []))}.\n")

    lines.append("## Research Gaps\n")
    gap_path = Path("outputs/reports/research_gaps.md")
    if gap_path.exists():
        text = gap_path.read_text()
        for m in re.finditer(r'\*\*(.*?)\*\*\s*\((\d+) papers?\)', text):
            lines.append(f"- {m.group(1)} (only {m.group(2)} papers) requires further investigation.\n")

    lines.append("\n---\n*Draft generated by manuscript_copilot.py*")
    return "\n".join(lines)


def generate_literature_review(kb: Dict, evidence_df: pd.DataFrame, refs_df: pd.DataFrame) -> str:
    lines: List[str] = []
    lines.append("# Literature Review\n")

    for t in kb.get("themes", []):
        label = t.get("theme", "")
        papers = t.get("papers", [])
        keywords = t.get("keywords", [])
        lines.append(f"## {label}\n")
        lines.append(f"This theme encompasses {len(papers)} papers focusing on {', '.join(keywords[:3])}.")
        lines.append("Key contributions include:\n")
        for p_title in papers[:6]:
            # Find in papers_df if we have a reference
            match = refs_df[refs_df["Supporting_Paper"].str.contains(p_title[:50], na=False)]
            if not match.empty:
                row = match.iloc[0]
                lines.append(f"- {p_title} — {row['APA_Reference']}\n")
            else:
                lines.append(f"- {p_title}\n")
        lines.append("")

    lines.append("\n---\n*Draft generated by manuscript_copilot.py*")
    return "\n".join(lines)


def generate_methods(kb: Dict, evidence_df: pd.DataFrame) -> str:
    lines: List[str] = []
    lines.append("# Methods\n")

    lines.append("## Search Strategy\n")
    lines.append("A systematic search was conducted across multiple databases including "
                 "Crossref, OpenAlex, CORE, and additional sources. ")
    lines.append(f"A total of {kb.get('corpus_size', 0)} papers were retrieved and screened.\n")

    lines.append("## Inclusion Criteria\n")
    lines.append("Papers were included if they addressed themes related to the research domain. "
                 "No restrictions on study design were applied, provided the research was reported in English.\n")

    lines.append("## Data Extraction\n")
    if not evidence_df.empty:
        lines.append(f"Structured data were extracted from {len(evidence_df)} papers using standardised templates covering "
                     "objectives, methods, results, limitations, and conclusions.\n")
        lines.append("### Evidence Matrix\n")
        lines.append("| Paper | Objective | Methods | Results |\n")
        lines.append("|-------|-----------|---------|--------|\n")
        for _, row in evidence_df.head(8).iterrows():
            obj = str(row.get("Objective", ""))[:60]
            meth = str(row.get("Methods", ""))[:60]
            res = str(row.get("Results", ""))[:60]
            lines.append(f"| {row['Title'][:40]} | {obj} | {meth} | {res} |\n")

    lines.append("## Analysis\n")
    lines.append("Thematic analysis was conducted using a multi-method consensus approach "
                 "combining NMF, hierarchical clustering, and fixed k-means clustering.\n")

    lines.append("\n---\n*Draft generated by manuscript_copilot.py*")
    return "\n".join(lines)


def generate_discussion(kb: Dict, evidence_df: pd.DataFrame) -> str:
    lines: List[str] = []
    lines.append("# Discussion\n")

    lines.append("## Summary of Findings\n")
    lines.append(f"This review identified {kb.get('theme_count', 0)} major thematic clusters "
                 f"across {kb.get('corpus_size', 0)} publications. ")
    for t in kb.get("themes", []):
        label = t.get("theme", "")
        pc = t.get("paper_count", 0)
        lines.append(f"The **{label}** theme ({pc} papers) represents a {'well-' if pc >= 5 else ''}established area of inquiry.\n")

    lines.append("## Implications\n")
    lines.append("These findings have implications for research policy, funding priorities, and practice. "
                 "The thematic structure highlights both mature areas and underexplored niches.\n")

    lines.append("## Limitations\n")
    lines.append(f"This review is based on {kb.get('corpus_size', 0)} papers. "
                 "The small corpus size means theme structures are exploratory rather than definitive. "
                 "Additional databases and grey literature sources should be incorporated.\n")

    lines.append("## Future Directions\n")
    gap_path = Path("outputs/reports/research_gaps.md")
    if gap_path.exists():
        text = gap_path.read_text()
        for m in re.finditer(r'- (?:Investigate )?\*?\*?(.*?)\*?\*', text):
            lines.append(f"- Further research on {m.group(1)} is needed.\n")

    lines.append("\n---\n*Draft generated by manuscript_copilot.py*")
    return "\n".join(lines)


def generate_references_list(papers_df: pd.DataFrame) -> str:
    lines: List[str] = []
    lines.append("# References\n")
    refs = []
    for _, row in papers_df.iterrows():
        ref = _format_apa(row)
        if ref:
            refs.append(ref)
    for i, ref in enumerate(refs, 1):
        lines.append(f"[{i}] {ref}\n")
    lines.append("\n---\n*Generated by manuscript_copilot.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate manuscript drafts.")
    parser.add_argument("--papers", type=str, default="search_results.csv")
    parser.add_argument("--knowledge-base", type=str, default="knowledge_base.json")
    parser.add_argument("--evidence", type=str, default="outputs/evidence/evidence_matrix.csv")
    parser.add_argument("--claim-refs", type=str, default="outputs/references/claim_support_references.csv")
    parser.add_argument("--output-dir", type=str, default="outputs/manuscript")
    args = parser.parse_args()

    kb = load_knowledge_base(args.knowledge_base)
    evidence_df = load_evidence_matrix(args.evidence)
    refs_df = load_claim_refs(args.claim_refs)
    papers_df = pd.read_csv(args.papers) if Path(args.papers).exists() else pd.DataFrame()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sections = {
        "introduction": generate_introduction(kb, evidence_df, papers_df),
        "literature_review": generate_literature_review(kb, evidence_df, refs_df),
        "methods_draft": generate_methods(kb, evidence_df),
        "discussion_draft": generate_discussion(kb, evidence_df),
        "references": generate_references_list(papers_df),
    }

    for name, content in sections.items():
        path = out_dir / f"{name}.md"
        with open(path, "w") as f:
            f.write(content)
        log.info("Saved -> %s", path)

    print(f"\n--- Manuscript Copilot Complete ---")
    print(f"  Sections: {len(sections)}")
    print()


if __name__ == "__main__":
    main()
