#!/usr/bin/env python3
"""
project_manager.py — Track ongoing research activities including projects,
hypotheses, manuscripts, datasets, and grant opportunities.

Outputs
-------
outputs/projects/project_dashboard.md
outputs/projects/project_database.json
"""

from __future__ import annotations

import argparse
import json
import logging
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("project_manager")

DB_PATH = Path("outputs/projects/project_database.json")


def _load_db() -> Dict[str, Any]:
    if DB_PATH.exists():
        return json.loads(DB_PATH.read_text())
    return {
        "projects": [],
        "hypotheses": [],
        "manuscripts": [],
        "datasets": [],
        "grants": [],
        "_updated": datetime.now().isoformat(),
    }


def _save_db(db: Dict) -> None:
    db["_updated"] = datetime.now().isoformat()
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DB_PATH, "w") as f:
        json.dump(db, f, indent=2)


def track_projects(name: str = "Digital Literature Review",
                   status: str = "active",
                   description: str = "") -> Dict:
    db = _load_db()
    existing = [p for p in db["projects"] if p["name"] == name]
    if existing:
        existing[0]["status"] = status
        existing[0]["description"] = description
        existing[0]["updated_at"] = datetime.now().isoformat()
    else:
        db["projects"].append({
            "name": name,
            "status": status,
            "description": description,
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
        })
    _save_db(db)
    return db


def track_hypotheses(hyp_csv: str = "outputs/reports/hypothesis_bank.csv") -> Dict:
    df = pd.read_csv(hyp_csv) if Path(hyp_csv).exists() else pd.DataFrame()
    db = _load_db()
    if not df.empty:
        db["hypotheses"] = df.to_dict(orient="records")
    _save_db(db)
    return db


def track_manuscripts(manuscript_dir: str = "outputs/manuscript") -> Dict:
    md_dir = Path(manuscript_dir)
    db = _load_db()
    if md_dir.exists():
        db["manuscripts"] = [
            {"filename": f.name, "section": f.stem, "size_kb": round(f.stat().st_size / 1024, 1)}
            for f in sorted(md_dir.glob("*.md"))
        ]
    _save_db(db)
    return db


def track_datasets(dataset_csv: str = "outputs/reports/available_datasets.csv") -> Dict:
    df = pd.read_csv(dataset_csv) if Path(dataset_csv).exists() else pd.DataFrame()
    db = _load_db()
    if not df.empty:
        db["datasets"] = df.to_dict(orient="records")
    _save_db(db)
    return db


def track_grants(grant_dir: str = "outputs/grants") -> Dict:
    gr_dir = Path(grant_dir)
    db = _load_db()
    if gr_dir.exists():
        db["grants"] = [
            {"filename": f.name, "type": f.stem, "size_kb": round(f.stat().st_size / 1024, 1)}
            for f in sorted(gr_dir.glob("*.md"))
        ]
    _save_db(db)
    return db


def _generate_dashboard(db: Dict) -> str:
    lines: List[str] = []
    lines.append("# Project Dashboard\n")
    lines.append(f"- **Updated:** {db.get('_updated', '')}\n")

    lines.append("## Active Projects\n")
    for p in db.get("projects", []):
        lines.append(f"- **{p.get('name', '')}** ({p.get('status', '')})")
    lines.append("")

    lines.append("## Manuscripts\n")
    for m in db.get("manuscripts", []):
        lines.append(f"- {m.get('filename', '')} ({m.get('size_kb', '')} KB)")
    lines.append("")

    lines.append("## Hypotheses\n")
    h = len(db.get("hypotheses", []))
    lines.append(f"- {h} hypotheses in database")
    if h:
        themes = set()
        for hyp in db["hypotheses"]:
            if isinstance(hyp, dict) and "theme" in hyp:
                themes.add(hyp["theme"])
        lines.append(f"- Across {len(themes)} themes")
    lines.append("")

    lines.append("## Datasets\n")
    for d in db.get("datasets", [])[:5]:
        title = d.get("paper_title", "")[:60] if isinstance(d, dict) else str(d)[:60]
        lines.append(f"- {title}")
    lines.append("")

    lines.append("## Grants\n")
    for g in db.get("grants", []):
        lines.append(f"- {g.get('filename', '')}")

    lines.append("\n---\n*Generated by project_manager.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Research project manager.")
    parser.add_argument("--hypotheses", type=str, default="outputs/reports/hypothesis_bank.csv")
    parser.add_argument("--manuscript-dir", type=str, default="outputs/manuscript")
    parser.add_argument("--datasets", type=str, default="outputs/reports/available_datasets.csv")
    parser.add_argument("--grants-dir", type=str, default="outputs/grants")
    parser.add_argument("--output-dir", type=str, default="outputs/projects")
    args = parser.parse_args()

    db = track_projects(name="Digital Literature Review", status="active",
                        description="Systematic literature review pipeline")
    track_hypotheses(args.hypotheses)
    track_manuscripts(args.manuscript_dir)
    track_datasets(args.datasets)
    track_grants(args.grants_dir)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    dashboard = _generate_dashboard(db)
    with open(out_dir / "project_dashboard.md", "w") as f:
        f.write(dashboard)
    log.info("Saved -> %s", out_dir / "project_dashboard.md")

    print(f"\n--- Project Manager Complete ---")
    print()


if __name__ == "__main__":
    main()
