#!/usr/bin/env python3
"""
research_memory.py — Persistent research memory that tracks topics searched,
papers collected, themes generated, research gaps, projects, hypotheses,
and manuscripts across sessions.

Outputs
-------
outputs/dashboard/research_dashboard.md
outputs/dashboard/research_history.json
"""

from __future__ import annotations

import argparse
import json
import logging
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("research_memory")


def _load_json(path: Path) -> Dict:
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {}


def _load_md(path: Path) -> str:
    if path.exists():
        return path.read_text()
    return ""


def _load_csv(path: Path) -> pd.DataFrame:
    if path.exists():
        return pd.read_csv(path)
    return pd.DataFrame()


def update_memory(output_dir: Path) -> Dict[str, Any]:
    """Scan all pipeline outputs and build a research memory snapshot."""
    memory: Dict[str, Any] = {
        "_meta": {
            "updated": datetime.now().isoformat(),
            "version": "1.0",
        },
        "topics_searched": [],
        "papers_collected": 0,
        "themes_generated": [],
        "research_gaps": [],
        "projects": [],
        "hypotheses": [],
        "manuscripts": [],
    }

    # Papers
    papers_path = Path("search_results.csv")
    if papers_path.exists():
        df = pd.read_csv(papers_path)
        memory["papers_collected"] = len(df)
        if "title" in df.columns:
            memory["topics_searched"] = [str(t)[:100] for t in df["title"].dropna().head(5).tolist()]

    # Themes
    kb_path = Path("knowledge_base.json")
    if kb_path.exists():
        kb = _load_json(kb_path)
        memory["themes_generated"] = [
            {"name": t.get("theme", ""), "paper_count": t.get("paper_count", 0)}
            for t in kb.get("themes", [])
        ]

    # Gaps
    gaps_path = Path("outputs/reports/research_gaps.md")
    if gaps_path.exists():
        memory["research_gaps"] = _load_md(gaps_path)[:500]

    # Hypotheses
    hyp_path = Path("outputs/reports/hypothesis_bank.csv")
    if hyp_path.exists():
        hyp_df = _load_csv(hyp_path)
        memory["hypotheses"] = len(hyp_df)
        if "priority_score" in hyp_df.columns:
            memory["avg_hypothesis_priority"] = round(float(hyp_df["priority_score"].mean()), 3)

    # Manuscripts
    manuscript_dir = Path("outputs/manuscript")
    if manuscript_dir.exists():
        memory["manuscripts"] = [str(f.name) for f in sorted(manuscript_dir.glob("*.md"))]

    # Projects
    memory["projects"] = [
        {
            "name": "Digital Literature Review",
            "status": "active",
            "modules_created": sorted([
                f.stem for f in Path(".").glob("*.py")
                if f.stem not in ("venv", "__pycache__")
            ]),
        }
    ]

    # Dashboard summary
    dashboard_lines: List[str] = []
    dashboard_lines.append("# Research Dashboard\n")
    dashboard_lines.append(f"- **Last updated:** {memory['_meta']['updated']}")
    dashboard_lines.append(f"- **Papers collected:** {memory['papers_collected']}")
    dashboard_lines.append(f"- **Themes identified:** {len(memory['themes_generated'])}")
    dashboard_lines.append(f"- **Manuscripts drafted:** {len(memory['manuscripts'])}\n")

    if memory["themes_generated"]:
        dashboard_lines.append("## Themes\n")
        for t in memory["themes_generated"]:
            dashboard_lines.append(f"- {t['name']} ({t['paper_count']} papers)")

    if memory["manuscripts"]:
        dashboard_lines.append("\n## Manuscripts\n")
        for m in memory["manuscripts"]:
            dashboard_lines.append(f"- {m}")

    dashboard_lines.append("\n## Projects\n")
    for p in memory["projects"]:
        dashboard_lines.append(f"- **{p['name']}** ({p['status']})")
        dashboard_lines.append(f"  - {len(p['modules_created'])} modules")

    dashboard_lines.append("\n---\n*Generated by research_memory.py*")
    memory["dashboard_md"] = "\n".join(dashboard_lines)

    return memory


def main() -> None:
    parser = argparse.ArgumentParser(description="Persistent research memory.")
    parser.add_argument("--output-dir", type=str, default="outputs/dashboard")
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    memory = update_memory(out_dir)

    # Write JSON history
    json_path = out_dir / "research_history.json"
    with open(json_path, "w") as f:
        json.dump(memory, f, indent=2, ensure_ascii=False)
    log.info("Saved -> %s", json_path)

    # Write dashboard
    md_path = out_dir / "research_dashboard.md"
    with open(md_path, "w") as f:
        f.write(memory.get("dashboard_md", ""))
    log.info("Saved -> %s", md_path)

    print(f"\n--- Research Memory Update Complete ---")
    print(f"  Papers: {memory['papers_collected']}")
    print(f"  Themes: {len(memory['themes_generated'])}")
    print(f"  Manuscripts: {len(memory['manuscripts'])}")
    print()


if __name__ == "__main__":
    main()
