#!/usr/bin/env python3
"""
research_dashboard.py — Generate a comprehensive researcher dashboard
displaying active projects, current themes, emerging themes, research gaps,
future opportunities, datasets, manuscripts, grant concepts, and alerts.

Outputs
-------
outputs/dashboard/research_dashboard.md
"""

from __future__ import annotations

import argparse
import json
import logging
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("research_dashboard")


def _safe_read(path: str) -> str:
    p = Path(path)
    return p.read_text() if p.exists() else ""


def _safe_json(path: str) -> Dict:
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else {}


def _safe_csv(path: str) -> pd.DataFrame:
    p = Path(path)
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


def build_dashboard(output_dir: str = "outputs/dashboard") -> str:
    lines: List[str] = []
    lines.append("# Research Dashboard\n")
    lines.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    # --- Active Projects ---
    proj_db = _safe_json("outputs/projects/project_database.json")
    lines.append("## Active Projects\n")
    for p in proj_db.get("projects", []):
        lines.append(f"- **{p.get('name', '')}** — {p.get('status', '')}")
    lines.append("")

    # --- Current & Emerging Themes ---
    kb = _safe_json("knowledge_base.json")
    themes = kb.get("themes", [])
    lines.append("## Current Themes\n")
    for t in themes:
        lines.append(f"- **{t.get('theme', '')}** — {t.get('paper_count', 0)} papers, confidence {t.get('confidence', 0):.0%}")
    lines.append("")

    # Emerging themes from evolution report
    evo = _safe_json("outputs/reports/theme_evolution.json") if Path("outputs/reports/theme_evolution.json").exists() else {}
    emerging = evo.get("trending_themes", []) or evo.get("future_themes", [])
    if emerging:
        lines.append("## Emerging Themes\n")
        for t in emerging[:3]:
            lines.append(f"- {t.get('theme', '')}")
        lines.append("")

    # --- Research Gaps ---
    gaps = _safe_csv("outputs/reports/gap_confidence_scores.csv")
    lines.append("## Research Gaps\n")
    if not gaps.empty:
        for _, row in gaps.iterrows():
            lines.append(f"- **{row.get('theme', '')}** — score {row.get('gap_confidence_score', ''):.2f} ({row.get('verdict', '')})")
    lines.append("")

    # --- Future Opportunities ---
    opp = _safe_csv("outputs/reports/research_opportunities.csv")
    lines.append("## Future Opportunities\n")
    if not opp.empty:
        for _, row in opp.head(5).iterrows():
            lines.append(f"- **{row.get('theme', '')}** — {row.get('opportunity_score', '')} ({row.get('opportunity_level', '')})")
    lines.append("")

    # --- Datasets ---
    datasets = _safe_csv("outputs/reports/available_datasets.csv")
    lines.append("## Available Datasets\n")
    if not datasets.empty:
        for _, row in datasets.iterrows():
            lines.append(f"- {row.get('paper_title', '')[:60]} ({row.get('accessibility', '')})")
    lines.append("")

    # --- Manuscripts ---
    lines.append("## Manuscripts\n")
    man_dir = Path("outputs/manuscript")
    if man_dir.exists():
        for f in sorted(man_dir.glob("*.md")):
            lines.append(f"- {f.stem.replace('_', ' ').title()}")
    lines.append("")

    # --- Grant Concepts ---
    lines.append("## Grant Concepts\n")
    gr_dir = Path("outputs/grants")
    if gr_dir.exists():
        for f in sorted(gr_dir.glob("*.md")):
            lines.append(f"- {f.stem.replace('_', ' ').title()}")
    lines.append("")

    # --- Alerts ---
    alerts = _safe_read("outputs/alerts/semantic_alerts.md")
    if alerts:
        lines.append("## Recent Alerts\n")
        for line in alerts.split("\n")[:10]:
            if line.startswith("-"):
                lines.append(f"  {line}")
        lines.append("")

    # --- Evidence Summary ---
    ev_summary = _safe_read("outputs/evidence/evidence_summary.md")
    if ev_summary:
        lines.append("## Evidence Summary\n")
        for line in ev_summary.split("\n")[2:6]:
            lines.append(f"  {line}")
        lines.append("")

    lines.append("---\n*Generated by research_dashboard.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate research dashboard.")
    parser.add_argument("--output-dir", type=str, default="outputs/dashboard")
    args = parser.parse_args()

    dashboard = build_dashboard(args.output_dir)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / "research_dashboard.md", "w") as f:
        f.write(dashboard)
    log.info("Saved -> %s", out_dir / "research_dashboard.md")

    print(f"\n--- Research Dashboard Complete ---")
    print()


if __name__ == "__main__":
    main()
