#!/usr/bin/env python3
"""
research_brief.py — Generate a unified research brief aggregating all pipeline
outputs into a single comprehensive executive report.

Usage
-----
    python research_brief.py
        [--living-kb outputs/knowledge_base/living_knowledge_base.json]
        [--output outputs/reports/research_brief.md]
        [--papers search_results.csv]
        [--quick]   # Brief summary mode
"""

from __future__ import annotations

import argparse
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("research_brief")


def load_living_kb(path: Path) -> Dict[str, Any]:
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {}


def _summary_table(data: List[Dict], cols: List[str]) -> str:
    """Render a list of dicts as a markdown table."""
    if not data:
        return "_No data._"
    df = pd.DataFrame(data)
    available = [c for c in cols if c in df.columns]
    if not available:
        return "_No data._"
    return df[available].head(20).to_markdown(index=False)


def generate_brief(kb: Dict[str, Any], quick: bool = False) -> str:
    lines: List[str] = []
    meta = kb.get("_meta", {})

    lines.append("# Research Brief — Comprehensive Literature Analysis")
    lines.append("")
    lines.append(f"- **Generated:** {meta.get('updated', datetime.now().isoformat())}")
    lines.append(f"- **Mode:** {'Quick Summary' if quick else 'Full Report'}")
    lines.append("")

    # 1. Executive Summary
    lines.append("## 1. Executive Summary")
    kb_summary = kb.get("knowledge_base_summary", {})
    lines.append(f"")
    lines.append(f"- **Total papers analysed:** {kb_summary.get('paper_count', 'N/A')}")
    lines.append(f"- **Themes identified:** {kb_summary.get('theme_count', 'N/A')}")
    lines.append("")
    if quick:
        lines.append("_Quick summary mode — detailed sections omitted._")
        lines.append("")
        lines.append("## Key Outputs")
        for section in ["theme_classifications", "citation_intelligence", "hypothesis_bank",
                         "author_intelligence", "journal_intelligence", "methodology_profile",
                         "contradictions", "funding_alignment"]:
            if kb.get(section):
                lines.append(f"- {section.replace('_', ' ').title()}: data available")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by research_brief.py (quick mode)*")
        return "\n".join(lines)

    # 2. Theme Landscape
    lines.append("## 2. Theme Landscape")
    lines.append("")
    themes = kb.get("themes", [])
    if themes:
        lines.append("| Theme | Papers | Confidence | Keywords |")
        lines.append("|-------|--------|------------|----------|")
        for t in themes[:10]:
            label = t.get("theme", t.get("label", ""))
            pc = t.get("paper_count", "")
            conf = t.get("confidence", "")
            kw = ", ".join(t.get("keywords", [])[:5])
            lines.append(f"| {label} | {pc} | {conf} | {kw[:60]} |")
        if len(themes) > 10:
            lines.append(f"| _... and {len(themes)-10} more themes_ | | | |")
        lines.append("")

    # 3. Theme Evolution
    evo = kb.get("theme_evolution", {})
    if evo:
        lines.append("### Theme Evolution")
        for cat in ["redundant", "developing", "trending", "future"]:
            items = evo.get(f"{cat}_themes", [])
            if items:
                labels = [x.get("theme", "") for x in items[:5]]
                lines.append(f"- **{cat.title()}:** {', '.join(labels)}")
        lines.append("")

    # 4. Classification details
    cls = kb.get("theme_classifications", {})
    if cls:
        lines.append("### Classification Summary")
        for k, v in cls.items():
            if isinstance(v, list):
                lines.append(f"- **{k.replace('_', ' ').title()}:** {len(v)} themes")
        lines.append("")

    # 5. Citation Intelligence
    ci = kb.get("citation_intelligence", {})
    if ci:
        lines.append("## 3. Citation Intelligence")
        lines.append(f"- **Papers in citation graph:** {ci.get('paper_count', 0)}")
        fs = ci.get("graph_summary", {})
        if fs:
            lines.append(f"- **Nodes/Edges:** {fs.get('nodes', 'N/A')}/{fs.get('edges', 'N/A')}")
        lines.append("")
        if ci.get("foundational"):
            lines.append("### Foundational Papers")
            for p in ci["foundational"][:5]:
                title = p.get("title", "?")[:80]
                score = p.get("page_rank", "")
                lines.append(f"- {title} (PageRank: {score})")
            lines.append("")
        if ci.get("influential_authors"):
            lines.append("### Influential Authors")
            for a in ci["influential_authors"][:5]:
                name = a.get("author", a.get("name", "?"))[:40]
                score = a.get("betweenness", a.get("page_rank", ""))
                lines.append(f"- {name} (score: {score})")
            lines.append("")

    # 6. Hypothesis Bank
    hb = kb.get("hypothesis_bank", {})
    if hb.get("hypotheses"):
        lines.append("## 4. Hypothesis Bank")
        lines.append(f"- **Total hypotheses generated:** {hb.get('count', 0)}")
        lines.append("")
        lines.append(_summary_table(hb["hypotheses"][:5], [
            "theme", "gap_type", "priority_score", "research_question",
        ]))
        lines.append("")

    # 7. Author Intelligence
    ai = kb.get("author_intelligence", {})
    if ai.get("data"):
        lines.append("## 5. Author Intelligence")
        lines.append(_summary_table(ai["data"][:8], [
            "author", "role", "h_index", "institution", "paper_count",
        ]))
        lines.append("")

    # 8. Journal Intelligence
    ji = kb.get("journal_intelligence", {})
    if ji.get("data"):
        lines.append("## 6. Journal Intelligence")
        lines.append(_summary_table(ji["data"][:8], [
            "journal", "paper_count", "impact_estimate", "themes_covered",
        ]))
        lines.append("")

    # 9. Methodology Profile
    mp = kb.get("methodology_profile", {})
    if mp.get("data"):
        lines.append("## 7. Methodology Profile")
        lines.append(_summary_table(mp["data"][:10], [
            "method_type", "method_name", "themes_covered", "paper_count",
        ]))
        lines.append("")

    # 10. Research Gaps
    gaps = kb.get("research_gaps", "")
    if gaps:
        lines.append("## 8. Research Gaps")
        lines.append(gaps[:2000])
        lines.append("")

    # 11. Contradictions
    cont = kb.get("contradictions", "")
    if cont:
        lines.append("## 9. Contradictory Findings")
        lines.append(cont[:2000])
        lines.append("")

    # 12. Opportunity Ranking
    opp = kb.get("opportunity_ranking", {})
    if opp.get("data"):
        lines.append("## 10. Research Opportunities")
        lines.append(_summary_table(opp["data"][:5], [
            "theme", "opportunity_score", "opportunity_level",
        ]))
        lines.append("")

    # 13. Funding Alignment
    fa = kb.get("funding_alignment", {})
    if fa.get("data"):
        lines.append("## 11. Funding Alignment")
        lines.append(_summary_table(fa["data"][:5], [
            "funding_area", "alignment_score", "alignment_level",
        ]))
        lines.append("")

    # 14. Research Roadmap
    roadmap = kb.get("research_roadmap", "")
    if roadmap:
        lines.append("## 12. Research Roadmap")
        lines.append(roadmap[:2000])
        lines.append("")

    lines.append("---")
    lines.append("*Generated by research_brief.py*")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate unified research brief.")
    parser.add_argument("--living-kb", type=str, default="outputs/knowledge_base/living_knowledge_base.json")
    parser.add_argument("--output", type=str, default="outputs/reports/research_brief.md")
    parser.add_argument("--quick", action="store_true", help="Brief summary mode")
    parser.add_argument("--papers", type=str, default="search_results.csv")
    args = parser.parse_args()

    kb = load_living_kb(Path(args.living_kb))
    if not kb:
        log.warning("Living KB not found at %s; generating from intermediate files", args.living_kb)
        from living_knowledge_base import merge_all
        kb = merge_all(args)

    report = generate_brief(kb, quick=args.quick)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(report)
    log.info("Saved -> %s", out_path)

    print(f"\n--- Research Brief Complete ---")
    print(f"  Saved: {out_path}")
    print()


if __name__ == "__main__":
    main()
